data:
  input_train_path: "../data/raw/train.jsonl"
  input_test_path: "../data/raw/test.jsonl"
  processed_train_path: "../data/processed/train_features.csv"
  processed_test_path: "../data/processed/test_features.csv"
model:
  path: "../models"
  type: "xgboost"
  params:
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 200
    subsample: 0.8
output:
  path: "../output/submission.csv"